# Generated by Django 4.0.2 on 2022-03-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_project_description_alter_project_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, verbose_name='')),
                ('Description', models.TextField(max_length=800, verbose_name='')),
                ('StartDate', models.DateField(max_length=100, verbose_name='')),
                ('EndDate', models.DateField(max_length=100, verbose_name='')),
                ('Statut', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectManager',
            field=models.CharField(max_length=200),
        ),
    ]
