# Generated by Django 4.0.2 on 2022-03-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_project'),
        ('Projects', '0004_delete_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.appuser'),
        ),
    ]
